- name: Add Postgres 10 signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
- apt_repository:
    #     deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main
    state: present
- apt: name=postgresql-10 state=present allow_unauthenticated=yes
