- name: Check consul binary file exist
  stat: path=/usr/local/bin/consul
  register: consul
- name: Check consul-template binary file exist
  stat: path=/usr/local/bin/consul-template
  register: consultemplate

- name: Check installed version of Consul and save it in "currentversion"
  shell: consul version | grep Consul | cut -d' ' -f2 | cut -d'v' -f2
  register: cv
  ignore_errors: yes
  no_log: True
  changed_when: False
  when: consul.stat.exists
- set_fact: currentversion={{cv.stdout|default('')}}
  when: cv is defined

- name: "Download and install Consul {{version}}, current version: {{currentversion}}"
  unarchive:
    src: https://releases.hashicorp.com/consul/{{version}}/consul_{{version}}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  when: not consul.stat.exists or version != currentversion

- name: Install consul-template
  unarchive:
    src: https://releases.hashicorp.com/consul-template/0.19.4/consul-template_0.19.4_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  when: not consultemplate.stat.exists


- name: Consul-Template systemd startup script
  copy:
    src: files/consul-template.service
    dest: /etc/systemd/system/consul-template.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart consul-template

- name: Agent/Server systemd sturtup script
  template:
    src: templates/systemd-consul.j2
    dest: /etc/systemd/system/consul.service
    # validate: '/usr/sbin/visudo -cf %s'
    mode: 0644
  notify:
    - restart consul

# Configs
- name: Create data_dir (/var/consul)
  file:
    path: /var/consul
    state: directory
    mode: 0755

- file:
    path: /etc/consul.d
    state: directory
    mode: 0755
- file:
    path: /etc/consul.d/server
    state: directory
    mode: 0755
- file:
    path: /etc/consul.d/agent
    state: directory
    mode: 0755

- file:
    path: /etc/consul-template.d
    state: directory
    mode: 0755

# - name: Consul server configuration
#   copy:
#     src: files/server.hcl
#     dest: /etc/consul.d/server/config.hcl
#     owner: root
#     group: root
#     mode: 0644
#   notify:
#     - restart consul

# 1. Error while starting Consul Agent: data_dir cannot be empty!
#    Why happened: agent config was missing
- name: Consul {{mode}} configuration
  template:
    src: templates/config.j2
    dest: /etc/consul.d/{{mode}}/config.hcl
    # validate: '/usr/sbin/visudo -cf %s'
  notify:
    - restart consul


# to remove
- name: Remove old config.json
  file:
    path: /etc/consul.d/server/config.json
    state: absent
  notify:
    - restart consul


- name: Consul Template configuration
  copy:
    src: files/consul-template.cfg
    dest: /etc/consul-template.d/consul-template.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - restart consul-template


- name: start and enable Consul {{mode}}
  systemd:
    name: consul
    state: started
    enabled: yes
    daemon_reload: yes
  # when: mode == 'server'


- name: start and enable Consul-template
  systemd:
    name: consul-template
    state: started
    enabled: yes
    daemon_reload: yes
