- stat: path=/usr/bin/nodejs
  register: binfile
- name: get nodejs version
  shell: nodejs -v
  register: version
  changed_when: False

- name: Download setup_8.x
  get_url:
    url: https://deb.nodesource.com/setup_8.x
    dest: /tmp/setup_8.x
    mode: 0700
  when: not binfile.stat.exists or not "v8" in version.stdout

- name: asd
  shell: bash /tmp/setup_8.x
  when: not binfile.stat.exists or not "v8" in version.stdout

- name: install nodejs
  apt: name={{item}} state=latest
  with_items:
    - nodejs  # recourse manager
