- name: restart consul
  systemd:
    name: consul
    state: restarted
    daemon_reload: yes

- name: restart consul-template
  systemd:
    name: consul-template
    state: restarted
    daemon_reload: yes
